### PR TITLE
Fix compilation error

### PR DESCRIPTION
**Pull request by Mr-Andersen**
On newest version of Idris ([70d1505](https://github.com/idris-lang/Idris2/commit/70d1505c5c7aebe1bf5293c78d0f7aa20a0f65d1)) your lib didn't compile, because constructor MkTy [changed](https://github.com/idris-lang/Idris2/blob/70d1505c5c7aebe1bf5293c78d0f7aa20a0f65d1/libs/base/Language/Reflection/TTImp.idr#L110).
I just made the types match, because otherwise I would have spent years understanding Elab's internals, so please check that everything is semantically correct. The main library's code compiles fine though

### CODE REVIEW

**Comment by MarcelineVQ** [comment]
lgtm, thanks! :>

**Comment by MarcelineVQ** [comment]
I accidentally broke this right after merging your PR, should be fixed up now sorry!

**Comment by Mr-Andersen** [comment]
Oof
